# Generated by Django 3.0.6 on 2020-05-28 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='photo',
        ),
        migrations.AddField(
            model_name='portafolio',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portafolio',
            name='image',
            field=models.ImageField(default='media/images/zelda.jpg', upload_to='media/images'),
        ),
    ]
