# Generated by Django 3.0.6 on 2020-05-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_auto_20200528_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portafolio',
            new_name='Project',
        ),
    ]
