# Generated by Django 3.0.6 on 2020-05-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_auto_20200528_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='/zelda.jpg', upload_to='images/'),
        ),
    ]
