# Generated by Django 3.0.6 on 2020-05-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_auto_20200528_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='http://github.io', max_length=128),
        ),
    ]
