# Generated by Django 3.0.6 on 2020-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(default='This project was very interesting but challenging', max_length=200),
        ),
    ]
